### PR TITLE
Add Norwegian Apple

### PR DESCRIPTION
**Pull request by Dot32Dev**
Norwegian is cool
Add it :>

### CODE REVIEW

**Comment by illogicalapple** [comment]
ok
but
you gave me extra work
i might actually have to add forty nine more languages

**Comment by Dot32Dev** [comment]
say "apple in more than 50 languages" :>

**Comment by illogicalapple** [comment]
ok then :D

**Comment by illogicalapple** [comment]
(glad to be relieved of the work)

**Comment by Dot32Dev** [comment]
haha

**Pull request merged**
